# Generated by Django 5.0 on 2023-12-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.CharField(max_length=100)),
                ('image_field', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
